#:schema node_modules/wrangler/config-schema.json
name = "sublinkk-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "32888eae04ae4f84ab9d9d8403f6aed3" }
]

[assets]
directory = "./public"
